default_install_hook_types: [ pre-commit, prepare-commit-msg, commit-msg, post-commit ]
default_stages: [ pre-commit, commit-msg ]
repos:
  - repo: local
    hooks:
    - id: black
      alias: run-fmt
      name: Format code (Black)
      entry: black
      language: python
      types: [python]
      verbose: true
      stages: [ pre-commit ]
    - id: isort
      alias: run-sort
      name: Sort imports (isort)
      entry: isort
      language: python
      types: [python]
      verbose: true
      stages: [ pre-commit ]
    - id: flake8
      alias: run-lint
      name: Lint the codebase (flake8)
      entry: flake8
      language: python
      types: [python]
      verbose: true
      require_serial: true
      additional_dependencies: [Flake8-pyproject]
      stages: [ pre-commit ]
