- id: cz-prepare-msg
  name: Automatically generate a commit message
  entry: cz-prepare-msg
  language: python
  types: [ files ]
  stages: [ prepare-commit-msg ]
- id: cz-post-commit
  name: Backup the commit message and clean up
  entry: cz-post-commit
  language: python
  types: [ files ]
  stages: [ post-commit ]
