name: Update Coverage on Readme
on:
  push:

concurrency:
  group: covrme-master
  cancel-in-progress: true

permissions:
  contents: write
  checks: write
  pull-requests: write

jobs:
  update-coverage-on-readme:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Pytest coverage comment
        if: ${{ github.ref == 'refs/heads/master' }}
        id: pytest-cov
        uses: MishaKav/pytest-coverage-comment@main
        with:
          hide-comment: true
          pytest-xml-coverage-path: coverage.xml
          junitxml-path: junit/test-results.xml

      - name: Update Readme with Coverage Html
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          sed -i '/<!-- Pytest Coverage Comment:Begin -->/,/<!-- Pytest Coverage Comment:End -->/c\<!-- Pytest Coverage Comment:Begin -->\n\${{ steps.pytest-cov.outputs.coverageHtml }}\n<!-- Pytest Coverage Comment:End -->' ./README.md

      - name: Commit & Push changes to Readme
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: actions-js/push@master
        with:
          message: Update coverage on Readme
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
