name: Update Coverage on Readme

on:
  push:
    branches:
      - master

concurrency:
  group: covrme-master
  cancel-in-progress: true

permissions:
  contents: write
  checks: write
  pull-requests: write

jobs:
  update-coverage-on-readme:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - uses: abatilo/actions-poetry@v4
        with:
          poetry-version: "2.0.1"

      - name: Install runtime and test dependencies
        run: poetry install --without dev

      - name: Run tests
        run: poetry run pytest

      - name: Collect coverage report
        id: pytest-cov
        uses: MishaKav/pytest-coverage-comment@main
        with:
          hide-comment: true
          pytest-xml-coverage-path: coverage.xml
          junitxml-path: junit/test-results.xml

      - name: Update Readme with Coverage Html
        run: |
          sed -i '/<!-- Pytest Coverage Comment:Begin -->/,/<!-- Pytest Coverage Comment:End -->/c\<!-- Pytest Coverage Comment:Begin -->\n\${{ steps.pytest-cov.outputs.coverageHtml }}\n<!-- Pytest Coverage Comment:End -->' ./README.md

      - name: Commit & Push changes to Readme
        uses: actions-js/push@master
        with:
          message: Update coverage on Readme
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
